import { normalizeEspnLeague } from "../engine/league/normalizeEspnLeague";
import type { LeagueSnapshot } from "../engine/types";
// ESPN's private API is intentionally decoded at the normalization boundary.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Json=Record<string,any>;
function config(){const x={swid:process.env.ESPN_SWID,espnS2:process.env.ESPN_S2,leagueId:process.env.ESPN_LEAGUE_ID,teamId:process.env.ESPN_TEAM_ID,seasonId:Number(process.env.ESPN_SEASON_ID)};const missing=Object.entries(x).filter(([,v])=>!v).map(([k])=>k);if(missing.length)throw new Error(`ESPN environment configuration is incomplete: ${missing.join(", ")}.`);return x as {swid:string;espnS2:string;leagueId:string;teamId:string;seasonId:number};}
async function get(url:URL,cookie:string,headers?:Record<string,string>){const r=await fetch(url,{headers:{Cookie:cookie,...headers},cache:"no-store",signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(`ESPN returned ${r.status}.`);return r.json() as Promise<Json>;}
function url(leagueId:string,season:number,views:string[],week?:number){const u=new URL(`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${season}/segments/0/leagues/${leagueId}`);views.forEach(v=>u.searchParams.append("view",v));if(week)u.searchParams.set("scoringPeriodId",String(week));return u;}
function merge(base:Json,weekly:Json[]){const map=new Map<string,Json[]>();for(const response of [base,...weekly])for(const team of response.teams??[])for(const entry of team.roster?.entries??[]){const p=entry.playerPoolEntry?.player;if(!p?.id)continue;const old=map.get(String(p.id))??[];const keys=new Map(old.map(x=>[`${x.seasonId}:${x.statSourceId}:${x.statSplitTypeId}:${x.scoringPeriodId}`,x]));for(const stat of p.stats??[])keys.set(`${stat.seasonId}:${stat.statSourceId}:${stat.statSplitTypeId}:${stat.scoringPeriodId}`,stat);map.set(String(p.id),[...keys.values()]);}for(const team of base.teams??[])for(const entry of team.roster?.entries??[]){const p=entry.playerPoolEntry?.player;if(p?.id)p.stats=map.get(String(p.id))??p.stats??[];}return base;}
export async function loadLiveLeagueSnapshot(requestedWeek?:number):Promise<{snapshot:LeagueSnapshot;raw:Json}>{const e=config(),cookie=`espn_s2=${e.espnS2}; SWID=${e.swid}`,retrievedAt=new Date().toISOString(),views=["mSettings","mTeam","mRoster","mStandings","mMatchup","mStatus","mNav"],base=await get(url(e.leagueId,e.seasonId,views,requestedWeek),cookie),currentWeek=requestedWeek??Math.max(1,Number(base.scoringPeriodId)||Number(base.status?.currentMatchupPeriod)||1),regular=Number(base.settings?.scheduleSettings?.matchupPeriodCount)||18,playoffTeams=Number(base.settings?.scheduleSettings?.playoffTeamCount)||0,playoffLength=Number(base.settings?.scheduleSettings?.playoffMatchupPeriodLength)||1,finalWeek=Math.min(18,regular+(playoffTeams?Math.ceil(Math.log2(playoffTeams))*playoffLength:0)),weeks=Array.from({length:Math.max(1,finalWeek-currentWeek+1)},(_,i)=>currentWeek+i).filter(w=>w!==currentWeek),[weekly,free]=await Promise.all([Promise.all(weeks.map(w=>get(url(e.leagueId,e.seasonId,["mRoster"],w),cookie))),get(url(e.leagueId,e.seasonId,["kona_player_info"]),cookie,{"X-Fantasy-Filter":JSON.stringify({players:{filterStatus:{value:["FREEAGENT","WAIVERS"]},limit:250,sortPercOwned:{sortPriority:1,sortAsc:false}}})})]),merged=merge(base,weekly);merged.scoringPeriodId=currentWeek;return {snapshot:normalizeEspnLeague({raw:merged,freeAgents:free.players??[],leagueId:e.leagueId,season:e.seasonId,primaryTeamId:e.teamId,dataMode:"live",retrievedAt}),raw:merged};}
