import assert from "node:assert/strict";
import test from "node:test";
import artifactJson from "../../artifacts/v6-ridge-2022-2025.json";
import { buildManagerProfiles, captureLiveForecastExperiment, evaluateRoster, findBuyLowTargets, findSellHighCandidates, loadV6Artifact, modelMetrics, rankWaivers, searchTrades, type ForecastValidationStore, type LeagueIntelligence, type LeaguePlayer, type LeagueSnapshot, type LiveForecastSnapshot, type PlayerIntelligence } from "../../src/engine";

const player:LeaguePlayer={id:"p",name:"P",nflTeam:"BUF",primaryPosition:"WR",eligiblePositions:["WR"],forecasts:[{playerId:"p",week:3,mean:10,lower:5,upper:15,availabilityProbability:1,source:"ESPN",asOf:"2026-09-05T10:00:00.000Z",version:"espn"}],actuals:[{playerId:"p",week:2,points:14,source:"fixture",asOf:"2026-09-04T10:00:00.000Z"}],provenance:{source:"fixture",asOf:"2026-09-05T10:00:00.000Z",retrievedAt:"2026-09-05T10:00:00.000Z"}};
const makeSnapshot=(week=3):LeagueSnapshot=>({id:"v8-fixture",season:2026,currentWeek:week,name:"Fixture",primaryTeamId:"t",dataMode:"live",players:{p:{...player,forecasts:[...player.forecasts,...(week===4?[{...player.forecasts[0],week:4}]:[])]}},freeAgentIds:["p"],waiverPlayerIds:[],schedule:[],teams:[{id:"t",name:"T",ownerIds:[],record:{wins:0,losses:0,ties:0},roster:[]}],settings:{scoring:[{statId:1,points:1,raw:{}}],lineupSlots:[{id:"wr",espnSlotId:4,name:"WR",count:1,kind:"active",eligiblePositions:["WR"]}],rosterSize:1,positionLimits:{},irSlots:0,playoffWeeks:[],raw:{}},provenance:{source:"fixture",asOf:"2026-09-05T10:00:00.000Z",retrievedAt:"2026-09-05T10:00:00.000Z",version:"fixture-v1"}});
const intelligence:Record<string,PlayerIntelligence>={p:{fundamental:{playerId:"p",week:3,expectedPoints:11,median:11,floor:6,ceiling:16,uncertainty:5,baselinePoints:11,roleAdjustment:0,regressionAdjustment:0,trend:"stable",confidence:0.8,sources:[],modelVersion:"v4",expectedProduction:{regressionDirection:"neutral",confidence:1}},market:{playerId:"p",value:1,low:0,high:2,tier:1,liquidity:1,trend:"stable",confidence:1,sources:[],sufficientForMispricing:false,modelVersion:"market"},role:{trend:"stable",confidence:1,evidence:[]},playerId:"p",position:"WR",fundamentalPercentile:50,fundamentalTier:1,classification:"FAIR",confidence:"medium",optionValue:0,evidence:[],risks:[],buyLow:undefined,sellHigh:undefined} as unknown as PlayerIntelligence};
const usage={p:[1,2].map(week=>({playerId:"p",season:2026,week,games:1,metrics:{targets:6,targetShare:.2,actualFantasyPoints:10+week},provenance:{source:"fixture",asOf:"2026-09-05T10:00:00.000Z",retrievedAt:"2026-09-05T10:00:00.000Z"}}))};
function store(rows:LiveForecastSnapshot[]=[], outcomes:unknown[]=[]):ForecastValidationStore{return {appendForecasts:async xs=>{for(const x of xs)if(!rows.some(y=>y.id===x.id))rows.push(x);},appendOutcomes:async xs=>{outcomes.push(...xs);},forecasts:async()=>rows,outcomes:async()=>outcomes as never};}
const game=(week:number,kickoff="2026-09-06T17:00:00.000Z")=>({gameId:`g${week}`,season:2026,week,homeTeam:"BUF",awayTeam:"NYJ",kickoffAt:kickoff,status:"scheduled" as const});
const options=(snapshot:LeagueSnapshot, artifact:Parameters<typeof captureLiveForecastExperiment>[0]["artifact"], validationStore:ForecastValidationStore, schedule:()=>Promise<ReturnType<typeof game>[]>, now="2026-09-05T10:00:00.000Z")=>({snapshot,usage,intelligence,artifact,scheduleProvider:{getSeason:schedule},store:validationStore,now:()=>now});
const stable=(value:unknown)=>JSON.stringify(value,(key,value)=>key==="instrumentation"?undefined:value);

test("V8 capture leaves V1 roster, trade, waiver, signal, and manager outputs unchanged",async()=>{const snapshot=makeSnapshot(),leagueIntelligence={asOf:"2026-09-05T10:00:00.000Z",modelVersion:"fixture",players:intelligence,buyLow:[],sellHigh:[],dataWarnings:[]} as unknown as LeagueIntelligence,production=()=>stable({roster:evaluateRoster(snapshot,"t"),trades:searchTrades("t",snapshot,{maxFinalResults:1},leagueIntelligence),waivers:rankWaivers("t",snapshot,{maxFinalResults:1},leagueIntelligence),buyLow:findBuyLowTargets("t",snapshot,leagueIntelligence),sellHigh:findSellHighCandidates("t",snapshot,leagueIntelligence),manager:buildManagerProfiles(snapshot)}),before=production();await captureLiveForecastExperiment({...options(snapshot,loadV6Artifact(artifactJson),store(),async()=>[game(3)]),intelligence:leagueIntelligence});assert.equal(production(),before);});

test("V8 missing artifact preserves ESPN/V4 and reports an explicit artifact diagnostic",async()=>{const rows:LiveForecastSnapshot[]=[];const result=await captureLiveForecastExperiment(options(makeSnapshot(),{status:"MISSING",diagnostic:"missing"},store(rows),async()=>[game(3)]));assert.equal(result.diagnostics.v6,0);assert.equal(result.diagnostics.espn,1);assert.equal(result.diagnostics.v4,1);assert.equal(result.diagnostics.artifactStatus,"MISSING");});
test("V8 READY artifact with provider failure yields UNKNOWN_LOCK without identity failures",async()=>{const result=await captureLiveForecastExperiment(options(makeSnapshot(),loadV6Artifact(artifactJson),store(),async()=>{throw new Error("schedule down");}));assert.equal(result.diagnostics.v6,1);assert.equal(result.diagnostics.kickoffUnknown,3);assert.equal(result.diagnostics.identityMappingFailures,0);assert.equal(result.snapshots.find(x=>x.source==="V6")?.lockState,"UNKNOWN_LOCK");});
test("V8 missing kickoff is excluded from comparison and exact kickoff is POST_LOCK",async()=>{const rows:LiveForecastSnapshot[]=[];const validationStore=store(rows);const unknown=await captureLiveForecastExperiment(options(makeSnapshot(),loadV6Artifact(artifactJson),validationStore,async()=>[]));assert.equal(unknown.comparisonSets,0);const post=await captureLiveForecastExperiment(options(makeSnapshot(),loadV6Artifact(artifactJson),validationStore,async()=>[game(3)],"2026-09-06T17:00:00.000Z"));assert.equal(post.snapshots.find(x=>x.source==="V6")?.lockState,"POST_LOCK");});
test("V8 persistence failure is represented and outcome-backed comparison survives revisions",async()=>{const failing:ForecastValidationStore={appendForecasts:async()=>{throw new Error("write failed");},appendOutcomes:async()=>{},forecasts:async()=>[],outcomes:async()=>[]};const failed=await captureLiveForecastExperiment(options(makeSnapshot(),loadV6Artifact(artifactJson),failing,async()=>[game(3)]));assert.equal(failed.diagnostics.persistence,"FAILED");assert.match(failed.diagnostics.persistenceError!,/write failed/);
  const rows:LiveForecastSnapshot[]=[];const actuals=[...player.actuals!,{playerId:"p",week:3,points:17,source:"fixture",asOf:"2026-09-06T20:00:00.000Z"}];const first=makeSnapshot(3);first.players.p.actuals=actuals;const validationStore=store(rows);await captureLiveForecastExperiment(options(first,loadV6Artifact(artifactJson),validationStore,async()=>[game(3)]));const second=makeSnapshot(4);second.players.p.actuals=actuals;const revised=await captureLiveForecastExperiment(options(second,loadV6Artifact(artifactJson),validationStore,async()=>[game(3),game(4,"2026-09-13T17:00:00.000Z")],"2026-09-12T10:00:00.000Z"));assert.ok(revised.comparisonSets>=1);assert.equal(modelMetrics((await import("../../src/engine")).buildComparisonSets(rows,[{leagueId:"v8-fixture",playerId:"p",season:2026,week:3,fantasyPoints:17,active:true,gameCompletedAt:"2026-09-06T20:00:00.000Z",provenance:[]}]),"V6").samples,1);assert.equal(rows.filter(x=>x.source==="V6").length,2);});
test("V8 capture is shadow-only and does not mutate the production snapshot or intelligence inputs",async()=>{const snapshot=makeSnapshot();const beforeSnapshot=JSON.stringify(snapshot),beforeIntelligence=JSON.stringify(intelligence);await captureLiveForecastExperiment(options(snapshot,loadV6Artifact(artifactJson),store(),async()=>[game(3)]));assert.equal(JSON.stringify(snapshot),beforeSnapshot);assert.equal(JSON.stringify(intelligence),beforeIntelligence);});

test("V8 distinguishes usage-provider outages and attributable identity failures from missing history",async()=>{
  const artifact=loadV6Artifact(artifactJson), snapshot=makeSnapshot();
  const unavailable=await captureLiveForecastExperiment({...options(snapshot,artifact,store(),async()=>[game(3)]),usageDiagnostic:{provider:"nflverse weekly player stats",status:"unavailable",retrievedAt:"2026-09-05T10:00:00.000Z",records:0,mapped:0}});
  assert.equal(unavailable.diagnostics.insufficientCurrentSeasonFeatures,0);assert.equal(unavailable.diagnostics.usageProviderErrors,1);assert.equal(unavailable.diagnostics.playerDiagnostics?.[0].reason,"USAGE_PROVIDER_UNAVAILABLE");
  const identity=await captureLiveForecastExperiment({...options(snapshot,artifact,store(),async()=>[game(3)]),usage:{},usageDiagnostic:{provider:"nflverse weekly player stats",status:"partial",retrievedAt:"2026-09-05T10:00:00.000Z",records:1,mapped:0,identityAttempts:1,identityFailures:1,identityFailurePlayerIds:["p"]}});
  assert.equal(identity.diagnostics.insufficientCurrentSeasonFeatures,0);assert.equal(identity.diagnostics.identityMappingFailures,1);assert.equal(identity.diagnostics.identityMappingFailurePlayers,1);assert.equal(identity.diagnostics.playerDiagnostics?.[0].reason,"IDENTITY_MAPPING_FAILURE");
});

test("V8 kickoff coverage is player-based and interval revisions remain append-only",async()=>{
  const snapshot=makeSnapshot(), loaded=loadV6Artifact(artifactJson);assert.equal(loaded.status,"READY");if(loaded.status!=="READY")return;
  const rows:LiveForecastSnapshot[]=[], validationStore=store(rows);
  const first=await captureLiveForecastExperiment(options(snapshot,loaded,validationStore,async()=>[game(3)]));
  assert.deepEqual(first.diagnostics.kickoffCoverage,{eligible:1,mapped:1,unmapped:0});assert.equal(first.diagnostics.kickoffMapped,1);
  const revised=structuredClone(loaded);revised.artifact.models.find(model=>model.position==="WR"&&model.horizon==="next1")!.residualStd+=1;
  await captureLiveForecastExperiment(options(snapshot,revised,validationStore,async()=>[game(3)]));
  assert.equal(rows.filter(row=>row.source==="V6").length,2);
});
