/* eslint-disable @typescript-eslint/no-explicit-any */
import { env } from "cloudflare:workers";
import type { ForecastValidationStore, LiveForecastSnapshot, PlayerOutcome } from "../src/engine/intelligence/liveValidation";
let ready=false;
async function ensure(){
  if(!env.DB)throw new Error("Forecast persistence unavailable: DB binding is missing.");
  if(ready)return;
  await env.DB.batch([
    env.DB.prepare("CREATE TABLE IF NOT EXISTS live_forecast_snapshots (id TEXT PRIMARY KEY, league_id TEXT NOT NULL, season INTEGER NOT NULL, week INTEGER NOT NULL, player_id TEXT NOT NULL, generated_at TEXT NOT NULL, source TEXT NOT NULL, expected_points REAL NOT NULL, lower_points REAL, upper_points REAL, availability_probability REAL, injury_status TEXT, model_version TEXT NOT NULL, league_snapshot_version TEXT NOT NULL, kickoff_time TEXT, lock_state TEXT NOT NULL, position TEXT, artifact_version TEXT, trained_through TEXT, forecast_horizon TEXT, feature_through_week INTEGER, feature_data_as_of TEXT, game_id TEXT, capture_phase TEXT)"),
    env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_live_forecasts_lookup ON live_forecast_snapshots (league_id, season, week, player_id, source, generated_at)"),
    env.DB.prepare("CREATE TABLE IF NOT EXISTS player_outcomes (id TEXT PRIMARY KEY, league_id TEXT NOT NULL, season INTEGER NOT NULL, week INTEGER NOT NULL, player_id TEXT NOT NULL, fantasy_points REAL NOT NULL, active INTEGER NOT NULL, game_completed_at TEXT NOT NULL, position TEXT, provenance_json TEXT NOT NULL)"),
  ]);
  const columns=await env.DB.prepare("PRAGMA table_info(live_forecast_snapshots)").all<{name:string}>();
  const known=new Set(columns.results.map(x=>x.name));
  for(const [name,type] of [["artifact_version","TEXT"],["trained_through","TEXT"],["forecast_horizon","TEXT"],["feature_through_week","INTEGER"],["feature_data_as_of","TEXT"],["game_id","TEXT"],["capture_phase","TEXT"]] as const)if(!known.has(name))await env.DB.prepare(`ALTER TABLE live_forecast_snapshots ADD COLUMN ${name} ${type}`).run();
  ready=true;
}
const outcomeId=(x:PlayerOutcome)=>`${x.leagueId}:${x.season}:${x.week}:${x.playerId}:${x.gameCompletedAt}`;
const row=(r:any):LiveForecastSnapshot=>({id:r.id,leagueId:r.league_id,season:r.season,week:r.week,playerId:r.player_id,generatedAt:r.generated_at,source:r.source,expectedPoints:r.expected_points,lower:r.lower_points??undefined,upper:r.upper_points??undefined,availabilityProbability:r.availability_probability??undefined,injuryStatus:r.injury_status??undefined,modelVersion:r.model_version,leagueSnapshotVersion:r.league_snapshot_version,kickoffTime:r.kickoff_time??undefined,gameId:r.game_id??undefined,lockState:r.lock_state,position:r.position??undefined,artifactVersion:r.artifact_version??undefined,trainedThrough:r.trained_through??undefined,forecastHorizon:r.forecast_horizon??undefined,featureThroughWeek:r.feature_through_week??undefined,featureDataAsOf:r.feature_data_as_of??undefined,capturePhase:r.capture_phase??undefined});
export const forecastValidationStore:ForecastValidationStore={
  async appendForecasts(rows){if(!rows.length)return;await ensure();for(let i=0;i<rows.length;i+=50)await env.DB!.batch(rows.slice(i,i+50).map(r=>env.DB!.prepare("INSERT OR IGNORE INTO live_forecast_snapshots (id,league_id,season,week,player_id,generated_at,source,expected_points,lower_points,upper_points,availability_probability,injury_status,model_version,league_snapshot_version,kickoff_time,lock_state,position,artifact_version,trained_through,forecast_horizon,feature_through_week,feature_data_as_of,game_id,capture_phase) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(r.id,r.leagueId,r.season,r.week,r.playerId,r.generatedAt,r.source,r.expectedPoints,r.lower??null,r.upper??null,r.availabilityProbability??null,r.injuryStatus??null,r.modelVersion,r.leagueSnapshotVersion,r.kickoffTime??null,r.lockState,r.position??null,r.artifactVersion??null,r.trainedThrough??null,r.forecastHorizon??null,r.featureThroughWeek??null,r.featureDataAsOf??null,r.gameId??null,r.capturePhase??null)));},
  async appendOutcomes(rows){if(!rows.length)return;await ensure();for(let i=0;i<rows.length;i+=50)await env.DB!.batch(rows.slice(i,i+50).map(r=>env.DB!.prepare("INSERT OR IGNORE INTO player_outcomes (id,league_id,season,week,player_id,fantasy_points,active,game_completed_at,position,provenance_json) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(outcomeId(r),r.leagueId,r.season,r.week,r.playerId,r.fantasyPoints,r.active?1:0,r.gameCompletedAt,r.position??null,JSON.stringify(r.provenance))));},
  async forecasts(leagueId,season){await ensure();const q=await env.DB!.prepare("SELECT * FROM live_forecast_snapshots WHERE league_id=? AND season=?").bind(leagueId,season).all<any>();return q.results.map(row);},
  async outcomes(leagueId,season){await ensure();const q=await env.DB!.prepare("SELECT * FROM player_outcomes WHERE league_id=? AND season=?").bind(leagueId,season).all<any>();return q.results.map(r=>({leagueId:r.league_id,playerId:r.player_id,season:r.season,week:r.week,fantasyPoints:r.fantasy_points,active:Boolean(r.active),gameCompletedAt:r.game_completed_at,position:r.position??undefined,provenance:JSON.parse(r.provenance_json)}));},
};
