import type { LeagueSnapshot, LeaguePlayer } from "../types";
import { validateLeagueSnapshot } from "../league/validateLeagueSnapshot";
import { buildV6FeatureRow, type HistoricalWeeklyStat } from "./calibration";
import { buildComparisonSets, captureForecastSnapshots, outcomesFromLeaguePlayers, predictWithV6, type CaptureDiagnostics, type ForecastValidationStore, type LiveForecastSnapshot, type V6PlayerDiagnostic } from "./liveValidation";
import type { LeagueIntelligence, UsageSnapshot } from "./types";
import { gameForTeam, type NFLGameSchedule } from "./providers/nflverseSchedule";
import type { V6ArtifactLoadResult } from "./v6Artifact";

export interface LiveForecastCaptureOptions {
  snapshot:LeagueSnapshot; usage:Record<string,UsageSnapshot[]>; usageDiagnostic?:import("./types").ProviderDiagnostic; intelligence:LeagueIntelligence|Record<string,LeagueIntelligence["players"][string]>;
  artifact?:V6ArtifactLoadResult; artifactLoader?:()=>V6ArtifactLoadResult; scheduleProvider:{getSeason(season:number):Promise<NFLGameSchedule[]>}; store:ForecastValidationStore; now?:()=>string;
}
export interface LiveForecastCaptureResult { diagnostics:CaptureDiagnostics; snapshots:LiveForecastSnapshot[]; comparisonSets:number; }
const skill=new Set(["QB","RB","WR","TE"]);
const capturePhase=(generatedAt:string,kickoff?:string,lock?:LiveForecastSnapshot["lockState"]):LiveForecastSnapshot["capturePhase"]=>{
  if(lock==="POST_LOCK")return "POST_LOCK"; if(!kickoff)return "EARLY_WEEK"; return (Date.parse(kickoff)-Date.parse(generatedAt))/36e5<=72?"MID_WEEK":"EARLY_WEEK";
};
function featureStats(player:LeaguePlayer, rows:UsageSnapshot[]):(HistoricalWeeklyStat & {provenance:{source:string;asOf:string;retrievedAt:string;version?:string}})[]{return rows.map(x=>({playerId:player.id,season:x.season??0,week:x.week,position:player.primaryPosition as "QB"|"RB"|"WR"|"TE",active:true,fantasyPoints:x.metrics.actualFantasyPoints,targets:x.metrics.targets,targetShare:x.metrics.targetShare,carries:x.metrics.carries,carryShare:x.metrics.carryShare,airYardShare:x.metrics.airYardShare,passAttempts:x.metrics.passAttempts,touchdowns:x.metrics.touchdowns,provenance:x.provenance}));}
export async function captureLiveForecastExperiment(options:LiveForecastCaptureOptions):Promise<LiveForecastCaptureResult>{
  const started=performance.now(), generatedAt=(options.now??(()=>new Date().toISOString()))(), s=options.snapshot;
  const validation=validateLeagueSnapshot(s); if(validation.status!=="READY")throw new Error(`League snapshot is not validated: ${validation.missingRequirements.join(", ")}`);
  const artifactStart=performance.now(), artifact=options.artifact??options.artifactLoader?.(); const artifactMs=performance.now()-artifactStart;
  const scheduleStart=performance.now(); let games:NFLGameSchedule[]=[]; try{games=await options.scheduleProvider.getSeason(s.season);}catch{games=[];} const scheduleMs=performance.now()-scheduleStart;
  const intelligence=("players" in options.intelligence?options.intelligence.players:options.intelligence) as Record<string,LeagueIntelligence["players"][string]>;
  const raw=captureForecastSnapshots(s.id,s.season,s.currentWeek,s.players,intelligence,generatedAt,s.provenance.version??"snapshot");
  const base=raw.map(x=>{const game=gameForTeam(games,s.players[x.playerId]?.nflTeam??"",x.week);if(!game)return {...x,lockState:"UNKNOWN_LOCK" as const,capturePhase:"EARLY_WEEK" as const};const lockState:LiveForecastSnapshot["lockState"]=Date.parse(generatedAt)<Date.parse(game.kickoffAt)?"PRE_LOCK":"POST_LOCK";return {...x,gameId:game.gameId,kickoffTime:game.kickoffAt,lockState,capturePhase:capturePhase(generatedAt,game.kickoffAt,lockState)};});
  const featureStart=performance.now(), v6:LiveForecastSnapshot[]=[], playerDiagnostics:V6PlayerDiagnostic[]=[]; let attempted=0, insufficient=0, missing=0, inferenceMs=0;
  const eligible=Object.values(s.players).filter(p=>skill.has(p.primaryPosition));
  const usageUnavailable=options.usageDiagnostic?.status==="unavailable", identityFailurePlayerIds=new Set(options.usageDiagnostic?.identityFailurePlayerIds??[]); let usageProviderErrors=0, identityFailurePlayers=0;
  if(artifact?.status!=="READY") for(const player of eligible)playerDiagnostics.push({playerId:player.id,requiredFeatures:[],availableFeatures:[],missingFeatures:[],inferenceProduced:false,reason:"ARTIFACT_ERROR"});
  if(artifact?.status==="READY") for(const player of eligible){
    attempted++; const model=artifact.artifact.models.find(m=>m.position===player.primaryPosition&&m.horizon==="next1")!; const required=[...model.featureNames];
    if(usageUnavailable){usageProviderErrors++;playerDiagnostics.push({playerId:player.id,requiredFeatures:required,availableFeatures:[],missingFeatures:required,inferenceProduced:false,code:"V6_UNAVAILABLE_FOR_PLAYER",reason:"USAGE_PROVIDER_UNAVAILABLE"});continue;}
    const rows=featureStats(player,options.usage[player.id]??[]), built=buildV6FeatureRow(rows,player.primaryPosition as "QB"|"RB"|"WR"|"TE");
    if(!built&&identityFailurePlayerIds.has(player.id)){identityFailurePlayers++;playerDiagnostics.push({playerId:player.id,requiredFeatures:required,availableFeatures:[],missingFeatures:required,inferenceProduced:false,code:"V6_UNAVAILABLE_FOR_PLAYER",reason:"IDENTITY_MAPPING_FAILURE"});continue;}
    if(!built){insufficient++;playerDiagnostics.push({playerId:player.id,requiredFeatures:required,availableFeatures:[],missingFeatures:required,inferenceProduced:false,code:"V6_UNAVAILABLE_FOR_PLAYER",reason:"INSUFFICIENT_CURRENT_SEASON_FEATURES"});continue;}
    const available=required.filter(f=>Number.isFinite((built.features as Record<string,number>)[f])), missingNames=required.filter(f=>!available.includes(f)); if(missingNames.length){missing++;playerDiagnostics.push({playerId:player.id,requiredFeatures:required,availableFeatures:available,missingFeatures:missingNames,inferenceProduced:false,code:"V6_UNAVAILABLE_FOR_PLAYER",reason:"MISSING_FEATURES"});continue;}
    const mapped=gameForTeam(games,player.nflTeam,s.currentWeek);
    const inferenceStart=performance.now(), prediction=predictWithV6(model,built.features,generatedAt); inferenceMs+=performance.now()-inferenceStart; if(!prediction){missing++;playerDiagnostics.push({playerId:player.id,requiredFeatures:required,availableFeatures:available,missingFeatures:[],inferenceProduced:false,code:"V6_UNAVAILABLE_FOR_PLAYER",reason:"MISSING_FEATURES"});continue;}
    const lockState:LiveForecastSnapshot["lockState"]=mapped?(Date.parse(generatedAt)<Date.parse(mapped.kickoffAt)?"PRE_LOCK":"POST_LOCK"):"UNKNOWN_LOCK";
    const artifactVersion=`${artifact.artifact.artifactVersion}:${artifact.artifact.createdAt}`, modelVersion=`${prediction.modelVersion}:${artifact.artifact.createdAt}`, item:Omit<LiveForecastSnapshot,"id">={leagueId:s.id,season:s.season,week:s.currentWeek,playerId:player.id,generatedAt,source:"V6",expectedPoints:prediction.expectedPoints,lower:prediction.lower,upper:prediction.upper,modelVersion,leagueSnapshotVersion:s.provenance.version??"snapshot",position:player.primaryPosition,gameId:mapped?.gameId,kickoffTime:mapped?.kickoffAt,lockState,capturePhase:capturePhase(generatedAt,mapped?.kickoffAt,lockState),artifactVersion,trainedThrough:model.trainedThrough,forecastHorizon:model.horizon,featureThroughWeek:built.featureThroughWeek,featureDataAsOf:rows.at(-1)?.provenance.asOf};
    v6.push({...item,id:`${s.id}:${s.season}:${s.currentWeek}:${player.id}:V6:${generatedAt}:${model.version}:${prediction.expectedPoints}:${prediction.lower}:${prediction.upper}:${artifactVersion}`}); playerDiagnostics.push({playerId:player.id,requiredFeatures:required,availableFeatures:available,missingFeatures:[],inferenceProduced:true});
  }
  const featureMs=performance.now()-featureStart, snapshots=[...base,...v6]; let persistence:"READY"|"FAILED"="READY", persistenceError:string|undefined; const persistStart=performance.now();
  try{await options.store.appendForecasts(snapshots);if(s.currentWeek>1)await options.store.appendOutcomes(outcomesFromLeaguePlayers(s.id,s.season,s.currentWeek-1,s.players,generatedAt));}catch(error){persistence="FAILED";persistenceError=error instanceof Error?error.message:"snapshot persistence failed";}
  let stored:LiveForecastSnapshot[]=[], outcomes=[] as Awaited<ReturnType<ForecastValidationStore["outcomes"]>>; if(persistence==="READY")try{stored=await options.store.forecasts(s.id,s.season);outcomes=await options.store.outcomes(s.id,s.season);}catch(error){persistence="FAILED";persistenceError=error instanceof Error?error.message:"snapshot read failed";}
  const comparisons=persistence==="READY"?buildComparisonSets(stored,outcomes):[], total=performance.now()-started, mappedPlayers=eligible.filter(player=>Boolean(gameForTeam(games,player.nflTeam,s.currentWeek))).length, preLock={ESPN:base.filter(x=>x.source==="ESPN"&&x.lockState==="PRE_LOCK").length,V4:base.filter(x=>x.source==="V4"&&x.lockState==="PRE_LOCK").length,V6:v6.filter(x=>x.lockState==="PRE_LOCK").length}, diagnostics:CaptureDiagnostics={eligible:eligible.length,kickoffMapped:mappedPlayers,kickoffCoverage:{eligible:eligible.length,mapped:mappedPlayers,unmapped:eligible.length-mappedPlayers},preLock,espn:base.filter(x=>x.source==="ESPN").length,v4:base.filter(x=>x.source==="V4").length,v6:v6.length,kickoffUnknown:snapshots.filter(x=>x.lockState==="UNKNOWN_LOCK").length,postLock:snapshots.filter(x=>x.lockState==="POST_LOCK").length,missingV6Features:missing,v6Attempted:attempted,insufficientCurrentSeasonFeatures:insufficient,usageProviderErrors,usageProviderStatus:options.usageDiagnostic?.status,identityMappingFailures:options.usageDiagnostic?.identityFailures??0,identityMappingFailurePlayers:identityFailurePlayers,artifactErrors:artifact?.status==="READY"?0:1,playerDiagnostics,comparisonSets:comparisons.length,persistence,persistenceError,artifactStatus:artifact?.status,artifactDiagnostic:artifact&&artifact.status!=="READY"?artifact.diagnostic:undefined,timings:{artifactLoad:artifactMs,schedule:scheduleMs,features:featureMs,inference:inferenceMs,persistence:performance.now()-persistStart,total}};
  return {snapshots,comparisonSets:comparisons.length,diagnostics};
}
